cache:
    #pipeline: [ ~/.npm ]
    event: [.]

jobs:
  main:
    annotations:
      beta.screwdriver.cd/timeout: 5 #minutes
    image: circleci/openjdk:8-jdk-node-browsers-legacy #node:8
    requires: [~pr, ~commit]
    steps:
      - ls: ls -l
      #- ls-npm: ls -l ~/.npm
      #- install: npm install --verbose
      - gradle: gradle build
      - touch: date >> date.txt

  next:
    image: circleci/openjdk:8-jdk-node-browsers-legacy
    requires: main
    steps:
      - ls: ls -l
      - cat: cat date.txt
      - java: java -cp ./build/classes/java/main/ helloworld.HelloWorld
