cache:
    #pipeline: [ ~/.npm ]
    event: [./build]

jobs:
  thisJobBuildsVariousComponentsAndPublishThem:
    annotations:
      beta.screwdriver.cd/timeout: 5 #minutes
    #image: circleci/openjdk:8-jdk-node-browsers-legacy #node:8
    image: node:8
    requires: ~pr #[~pr, ~commit]
    steps:
      - ls: ls -l
      - yarn: yarn cache dir
      #- ls-npm: ls -l ~/.npm
      #- install: npm install --verbose
      - gradle: gradle build
      - touch: date >> date.txt
      
  main:
    image: node:8
    requires: ~commit
    steps:
        - echo: echo ok
        
  next:
    image: node:8
    requires: [main, approve_deploy]
    steps:
        - echo: echo ok
        
  approve_deploy:
    image: node:8
    steps:
        - echo: echo ok
  
