cache:
    pipeline: [ ~/.npm ]

jobs:
  main:
    annotations:
      beta.screwdriver.cd/timeout: 5 #minutes
    image: node:8
    requires: [~pr, ~commit]
    steps:
      - ls: ls -l
      - ls-npm: ls -l ~/.npm
      - install: npm install --verbose
